/**
 * Banco de palavras embarcado offline para o e-Spiando Palavras.
 * Contém exatamente 10 temas com 100 palavras cada (totalizando 1000 palavras).
 * Todas as palavras estão pré-limpas (sem acentos, sem cedilha, sem hifens ou espaços, em caixa alta).
 */

export const embeddedThemes: Record<string, string[]> = {
  ANIMAIS: [
    "ABELHA", "AGUIA", "ALCE", "ALPACAS", "ANACONDA", "ANTILOPE", "ARANHA", "ARARA", "ASNO", "AVESTRUZ",
    "BACALHAU", "BALEIA", "BARATA", "BODE", "BOI", "BORBOLETA", "BUFALO", "BURRO", "CABRA", "CACHORRO",
    "CAGADO", "CAMALEAO", "CAMELO", "CANGURU", "CAPIVARA", "CARACOL", "CARANGUEJO", "CARNEIRO", "CASTOR", "CAVALO",
    "CEGONHA", "CHIMPANZE", "COALA", "COBRA", "COELHO", "COIOTE", "CORUJA", "CORVO", "CROCODILO", "DRAGOA",
    "ELEFANTE", "EMA", "ESCORPIAO", "ESQUILO", "FALCAO", "FLAMINGO", "FOCA", "FORMIGA", "GAFANHOTO", "GAIVOTA",
    "GALINHA", "GALO", "GAMBA", "GATO", "GAVIAO", "GIRAFA", "GORILA", "GOLFINHO", "GUEPARDA", "HENA",
    "HIPOPOTAMO", "IAC", "IGUANA", "JACARE", "JAGUAR", "JARARACA", "JOANINHA", "LAGARTA", "LAGARTIXA", "LAGOSTA",
    "LEAO", "LEBRE", "LEOPARDO", "LHAMA", "LOBO", "LONTRA", "LULA", "MACACO", "MAMUTE", "MARAVALHA",
    "MARRECO", "MICO", "MORCEGO", "MOSCA", "MULA", "NANDU", "ORANGOTANGO", "ORCA", "OVELHA", "PANDA",
    "PANTERA", "PATO", "PAVAO", "PEIXE", "PELICANO", "PERU", "PINGUIM", "PULGA", "PUMA", "PULPO"
  ],
  FRUTAS: [
    "ABACATE", "ABACAXI", "ACAI", "ACEROLA", "AMEIXA", "AMORA", "ANANAS", "ARATICUM", "ATEMOIA", "AVOCADO",
    "BACABA", "BACURI", "BANANA", "BARU", "BIRIBA", "BURITI", "CACAU", "CAJU", "CAQUI", "CARAMBOLA",
    "CEREJA", "CIDRA", "COCO", "CUPUACU", "DAMASCO", "FIGO", "FRAMBOESA", "FRUTADOKONDO", "FRUTADOPA0", "GABIROBA",
    "GOIABA", "GRAVIOLA", "GROSELHA", "GURUMIXAMA", "HEISTERIA", "INGA", "JABUTICABA", "JACA", "JAMBO", "JAMBOLAO",
    "JARACATIA", "JATOBA", "JENIPAPO", "JERIVA", "KIWI", "LARANJA", "LIMA", "LIMAO", "LITCHI", "MACA",
    "MACADAMIA", "MAMOES", "MANGA", "MANGABA", "MANGOSTAO", "MARACUJA", "MARMELO", "MELANCIA", "MELAO", "MIRTILO",
    "MORANGO", "MURICI", "NECTARINA", "NESPERA", "NOZ", "ORVALHA", "PECHECO", "PEQUI", "PERA", "PESSEGO",
    "PITANGA", "PITAYA", "PITAIA", "PITOMBA", "PUPUNHA", "RAMBUTAN", "ROMA", "SAPECA", "SERIGUELA", "TAMARA",
    "TAMARINDO", "TANGERINA", "TARUMA", "TUCUMA", "UMBU", "UVA", "UVAIA", "VELUDO", "XIXA", "ZABURRO",
    "ABIU", "ALFARROBA", "BILIMBI", "CAMUCAMU", "ESFREGUE", "FISALIS", "KUMQUAT", "MABOLO", "SALAK", "SAPOTI"
  ],
  PAISES: [
    "AFEGANISTAO", "ALBANIA", "ALEMANHA", "ANDORRA", "ANGOLA", "ARGENTINA", "ARGELIA", "ARMENIA", "AUSTRALIA", "AUSTRIA",
    "AZERBAIJAO", "BAHAMAS", "BANGLADESH", "BARBADOS", "BELGICA", "BELIZE", "BENIM", "BIELORUSSIA", "BOLIVIA", "BOTSUANA",
    "BRASIL", "BRUNEI", "BULGARIA", "BURUNDI", "BUTAO", "CABOVERDE", "CAMAROES", "CAMBOJA", "CANADA", "CATAR",
    "CAZAGUISTAO", "CHAD", "CHILE", "CHINA", "CHIPRE", "COLOMBIA", "CONGO", "COREIA", "COSTARICA", "CROACIA",
    "CUBA", "DINAMARCA", "DJIBUTI", "DOMINICA", "EGITO", "EQUADOR", "ERITREIA", "ESLOVAQUIA", "ESLOVENIA", "ESPANHA",
    "ESTADOSUNIDOS", "ESTONIA", "ETIOPIA", "FIJI", "FILIPINAS", "FINLANDIA", "FRANCA", "GABAO", "GAMBIA", "GANA",
    "GEORGIA", "GRECIA", "GUATEMALA", "GUIANA", "GUINE", "HAITI", "HOLANDA", "HONDURAS", "HUNGRIA", "IEMEN",
    "INDIA", "INDONESIA", "IRAQUE", "IRA", "IRLANDA", "ISLANDIA", "ISRAEL", "ITALIA", "JAMAICA", "JAPAO",
    "JORDANIA", "LAOS", "LESOTO", "LETONIA", "LIBANO", "LIBERIA", "LIBIA", "LITUANIA", "LUXEMBURGO", "MADAGASCAR",
    "MALASIA", "MALAUI", "MALDIVAS", "MALI", "MALTA", "MARROCOS", "MEXICO", "MOCAMBIQUE", "MONACO", "MONGOLIA"
  ],
  PROFISSOES: [
    "ADVOGADO", "AERONAUTA", "AGRONOMO", "ALFAIATE", "ALPINISTA", "ANESTESISTA", "APRESENTADOR", "ARQUEOLOGO", "ARQUITETO", "ARTISTA",
    "ASTRONAUTA", "ASTRONOMO", "ATLETA", "ATOR", "AUTOR", "AVIADOR", "BAILARINO", "BALCONISTA", "BANCARIO", "BARBEIRO",
    "BARMAN", "BIOLOGO", "BIOMEDICO", "BOMBEIRO", "BORRACHEIRO", "CABELEIREIRO", "CAIXA", "CAMINHONEIRO", "CANTOR", "CARPINTEIRO",
    "CARRETEIRO", "CARTEIRO", "CHEF", "CIENTISTA", "CIRURGIAO", "COBRADOR", "COZINHEIRO", "DENTISTA", "DEPUTADO", "DESIGNER",
    "DETETIVE", "DIGITADOR", "DIPLOMATA", "DIRETOR", "DOUTRINADOR", "ECOLOGISTA", "ECONOMISTA", "EDITOR", "EDUCADOR", "ELETRICISTA",
    "EMPREITEIRO", "ENFERMEIRO", "ENGENHEIRO", "ESCRITOR", "ESCULTOR", "ESTETICISTA", "ESTILISTA", "FARMACEUTICO", "FAXINEIRO", "FEIRANTE",
    "FILOSOFO", "FISICO", "FISIOTERAPEUTA", "FOTOGRAFO", "FUNILEIRO", "GEOLOGO", "GERENTE", "HISTORIADOR", "ILUSTRADOR", "IMPRESSOR",
    "INSTRUTOR", "JARDINEIRO", "JORNALISTA", "JUIZ", "LOCUTOR", "MANICURE", "MAQUINISTA", "MARCENEIRO", "MARUJO", "MATEMATICO",
    "MECANICO", "MEDICO", "MERGULHADOR", "MILITAR", "MINISTRO", "MOTORISTA", "MÚSICO", "NUTRICIONISTA", "OCULISTA", "OLEIRO",
    "PADEIRO", "PALHACO", "PASTOR", "PEDREIRO", "PEDIATRA", "PEIXEIRO", "PILOTO", "PINTOR", "POETA", "POLICIAL"
  ],
  TECNOLOGIA: [
    "ALGORITMO", "ANDROID", "ANTIVIRUS", "APLICATIVO", "ARQUIVO", "INFORMATICA", "BANCODEDADOS", "BITCOIN", "BLOG", "BLUETOOTH",
    "BYTE", "CELULAR", "CHIP", "CLIQUE", "COMPILADOR", "COMPUTADOR", "CONEXAO", "CONTROLLER", "CRIPTOGRAFIA", "CSS",
    "DATABASE", "DESENVOLVEDOR", "DISPOSITIVO", "DOWNLOAD", "DRIVE", "EMAIL", "EMULADOR", "ESCANEADOR", "FIBRAOPTICA", "FIREWALL",
    "FORMATAR", "FRAMEWORK", "GIGABYTE", "GOOGLAR", "GRAFICOS", "HACKER", "HARDWARE", "HTML", "IMPRESSORA", "INTERNET",
    "IPHONE", "JAVA", "JAVASCRIPT", "KEYBOARD", "LAPTOP", "LINK", "LINUX", "LOGICA", "LOGOUT", "MACINTOSH",
    "MEGABYTE", "MEMORIA", "MICROFONE", "MICROPROCESSADOR", "MODEM", "MONITOR", "MOUSAR", "MULTIMIDIA", "NANO", "NAVEGADOR",
    "NUVEM", "OFFLINE", "ONLINE", "OUTLOOK", "PAGE", "PAYPAL", "PHONES", "PIXEL", "PODCAST", "PORTAL",
    "PROGRAMDOR", "PROTOCOL", "PYTHON", "ROUTER", "ROBOT", "SATELLITE", "SCANNER", "SCREEN", "SECURITY", "SENSOR",
    "SERVIDOR", "SMARTPHONE", "SOFTWARE", "SUPORTEDEREDE", "TABLET", "TECLADO", "TECNOLOGIA", "TELETRANSPORTE", "TEMPLATES", "TERMINAL",
    "UPLOAD", "USUARIO", "VIRUS", "WEBCAM", "WEBSITE", "WIFI", "WINDOWS", "WORDPRESS", "XML", "YOUTUBE"
  ],
  ESPORTES: [
    "ALPINISMO", "ARREMESSO", "ATLETISMO", "AUTOMOBILISMO", "BADMINTON", "BASQUETEBOL", "BEISEBOL", "BIATLO", "BOLEIRA", "BOLICHE",
    "BOXE", "CANOAGEM", "CAPOEIRA", "CICLISMO", "CORRIDA", "CRICKET", "CROQUET", "DEPORTIVO", "DARTS", "EMBAIXADA",
    "ESGRIMA", "ESQUI", "FUTEBOL", "FUTSAL", "GINASTICA", "GOLFE", "HANDEBOL", "HIPISMO", "HOQUEI", "IATE",
    "JUDO", "KARATE", "KART", "KAYAK", "KUNG_FU", "LUCHA", "MARATONA", "MOTOCICLISMO", "NATACAO", "OLYMPICS",
    "PADEL", "PATINACAO", "PENTATLO", "PILATES", "PING_PONG", "POLO_AQUATICO", "PULO", "RAQUETE", "REMO", "RUGBY",
    "SAQUE", "SKATE", "SNOOKER", "SOFTEBOL", "SQUASH", "SURFE", "TAEKWONDO", "TENIS", "TIRO_COM_ARCO", "TRAVESSIA",
    "TRIATLO", "VELOCIDADE", "VELA", "VOLEIBOL", "WATERPOLO", "WINDSURFE", "XADREZ", "YOGA", "ZUMBA", "AEROBICA",
    "AMADOR", "ARRANQUE", "ARQUEIRO", "ATACANTE", "BALIZA", "CAMPEONATO", "CHUVEIRO", "DEFESA", "DESAFIO", "DESPORTO",
    "DOUBLE", "DRIBLE", "EMPATADO", "ENTRENADOR", "EQUIPE", "ESTADIO", "FINALISTA", "GINASIO", "GOLEADOR", "JOGADA"
  ],
  MÚSICA: [
    "ACORDE", "ACORDEAO", "AFINACAO", "AFINADOR", "ALBUM", "ALTOPALANTE", "AMPLIFICADOR", "APLAUSOS", "ARENA", "ARRANJO",
    "ARTISTA", "AUDIO", "BAIXO", "BANDA", "BANJO", "BARITONO", "BATERIA", "BATIDA", "BEMOL", "BLUES",
    "BOSSA_NOVA", "CABO", "CANCAO", "CANTOR", "CANTORIA", "CASTRAPETA", "CAVAQUINHO", "CELESTA", "CHAVE", "CLARINETE",
    "COELHO", "COMPOSITOR", "CONCERTO", "CONTRABAIXO", "CORAL", "CORNETA", "COURO", "DECIBEL", "DISCO", "DISCOGRAFIA",
    "DISCOTECA", "DUETO", "ECO", "ENSAIO", "ESPECTACULO", "ESTUDIO", "FADO", "FLAUTA", "FOLQUE", "FONOGRAFO",
    "GAITA", "GRAVACAO", "GUITARRA", "HARMONIA", "HARPA", "HINO", "INSTRUMENTO", "INTERVALO", "JAZZ", "LETRAS",
    "LIRA", "MAESTRO", "MELODIA", "METRONOMO", "MICROFONE", "MINUETO", "MIXAGEM", "MODULACAO", "MÚSICA", "MÚSICO",
    "NOTA", "OPERA", "ORQUESTRA", "OUVINTE", "PANDEIRO", "PAUSA", "PEDAL", "PERCUSSAO", "PIANO", "PINCEL",
    "PITACO", "PULSACOES", "QUARTETO", "RAP", "REGENCIA", "REMIX", "RITMO", "ROCK", "SANFONA", "SAXOFONE",
    "SINFONIA", "SOLO", "SOPRANO", "SOUNDTRACK", "TECLADO", "TENOR", "TIMBRE", "TRIANGULO", "TROMBONE", "TROMPETE"
  ],
  FILMES: [
    "ACAO", "ADAPTACAO", "ANIMACAO", "ANTEPREMERE", "ATOR", "ATRIZ", "AUDIO", "BILHETERIA", "CAMERA", "CAMEOPOD",
    "CARTAZ", "CENARIO", "CENOGRAFISTA", "CHOQUE", "CINEASTA", "CINEMA", "CINEMATECA", "CLAQUETE", "CLASSICO", "CODIRECAO",
    "COMEDIA", "COMPOSITOR", "CONTRATEMPO", "CRITICA", "CRONOLOGIA", "CURTAMETRAGEM", "DOCUMENTARIO", "DRAMA", "DUBLADOR", "DUBLAGEM",
    "ELENCO", "ENREDO", "EPICO", "ESPECTADOR", "ESSENCIAL", "ESTRUTURA", "ESTUDIO", "EXIBICAO", "FANTASIA", "FICCAO",
    "FILMAGEM", "FILME", "FOTOGRAFIA", "GELATINA", "GENERO", "GRANDEZA", "HISTORIA", "HOLLYWOOD", "ILUMINACAO", "IMAGEM",
    "INDIE", "INGRESSO", "LANAMENTO", "LEGENDADOR", "LEGENDA", "LENTE", "LOGLINE", "MAQUIAGEM", "MELODRAMA", "MONTAGEM",
    "MUDO", "NARRADOR", "NARRATIVO", "OPUS", "OSCAR", "PELICULA", "PIPOCA", "PLATEIA", "PRE-ESTREIA", "PREMIACOES",
    "PRODUTOR", "PRODUTORA", "PROJECAO", "PROJETOR", "PROTAGONISTA", "RAPIDO", "REALIZADOR", "ROTEIRISTA", "ROTEIRO", "SAGA",
    "SALA", "SANGUE", "SEQUENCIA", "SERIADO", "SESSAO", "SPINOFF", "SPOILER", "SUCESSO", "SUSPENSE", "TELAO",
    "TEMPORADA", "TERROR", "TRAILER", "TRILOGIA", "TRILHASONORA", "VILAO", "VIRTUAL", "VISUAL", "WESTERN", "ZOMBIE"
  ],
  CIENCIAS: [
    "ALQUIMIA", "ANATOMIA", "ANTROPOLOGIA", "ASTRONOMIA", "ATMOSFERA", "ATOMO", "BACTERIA", "BIOLOGIA", "BOTANICA", "CELULA",
    "CIENTISTA", "CLONAGEM", "COSMOS", "DESCOBERTA", "DOSAGEM", "ECOLOGIA", "ECOSISTEMA", "ELEMENTO", "EMPAQUE", "ENERGIA",
    "ENZIMA", "ESPACO", "ESPECIE", "EXPERIENCIA", "EVOLUCAO", "FISICA", "FOSSIL", "FUSION", "GENETICA", "GENOMA",
    "GEOGRAFIA", "GEOLOGIA", "GRAVIDADE", "HIPOTESE", "HISTOLOGIA", "IMUNOLOGIA", "LABORATORIO", "LASER", "MAGNETISMO", "MATERIA",
    "MATEMATICA", "MEDICINA", "METEORITO", "METEOROLOGIA", "METODO", "MICROBIOLOGIA", "MICROSCOPIO", "MINERAL", "MOLECULA", "NEUROCIENCIA",
    "NEUTRON", "NUCLEO", "OBSERVATORIO", "OCEANOGRAFIA", "ORGANISMO", "OXIGENIO", "PALEONTOLOGIA", "PATOLOGIA", "PESQUISA", "PLANETA",
    "POLIMERO", "PROTON", "QUIMICA", "RADIACAO", "REACAO", "RECIPIENTE", "SATELLITE", "SILICATO", "SISTEMA", "SOCIOLOGIA",
    "SOLUCAO", "TEORIA", "TERMODINAMICA", "TESOURO", "TRABALHO", "UNIVERSO", "VACINA", "VELOCIDADE", "VIRUS", "ZOOLOGIA",
    "ACIDO", "ALCALINO", "AMINOACIDO", "ASTEROIDE", "CROMOSSOMO", "DENSIDADE", "DNA", "ELEMENTARES", "EMISSÃO", "FISIOLOGIA",
    "GASOSO", "HEREDITARIO", "MUTACAO", "NEBULOSA", "REFRACAO", "ROCHOSA", "SINTESE", "TELESCOPIO", "TOXICOLOGIA", "ZOOPLANCTON"
  ],
  VEICULOS: [
    "AMBULANCIA", "AQUAPLANAR", "ASADelta", "AUTOCARRO", "AUTOMOVEL", "AVIAO", "BALAO", "BARCO", "BETONEIRA", "BICICLETA",
    "BILHETE", "BONDE", "BOTE", "CABLECAR", "CACADOR", "CACAMBA", "CACIQUE", "CAMINHAO", "CAMIONETE", "CANOA",
    "CARAVANA", "CARRINHO", "CARRO", "CARROCA", "CHARRETE", "CLUTCH", "COLECTIVO", "CORREIO", "CRUZADOR", "DEPORTIVO",
    "DIRIGIVEL", "DRAGSTER", "ELETRICO", "EMBARCACAO", "ESCAVADEIRA", "FOGUETE", "FURGAO", "GALEAO", "GAIOLA", "GONDOLA",
    "GUINCHO", "HELICOPTERO", "HIGHSPEED", "HILUX", "IATE", "JANGADA", "JEEP", "KART", "LANDROVER", "LIMUSINE",
    "LOCOMOTIVA", "LOTACAO", "MAQUINA", "METRO", "MONOPLANO", "MONOPLACE", "MOTO", "MOTOCICLETA", "MOTORHOME", "NAVIO",
    "ONIBUS", "PATINETE", "PERUA", "PICKUP", "PIBINA", "PRANCHA", "QUADRICICLO", "REBOQUE", "REVEZAMENTO", "ROQUETE",
    "SAILING", "SCOOTER", "SUBMARINO", "SUPERCAR", "TAXI", "TRATOR", "TREM", "TRICICLO", "TROLEBUS", "TURBINA",
    "VAN", "VEICULO", "VELOCIPEDE", "VESPA", "VELEIRO", "VIAGEM", "VIGIA", "VAGAO", "VOLANTE", "ZEPPELIN",
    "CARRETA", "COMANCHE", "CONVERSIVEL", "CROSS", "DIVISAO", "ESTRELA", "FREIO", "GURGEL", "MILITAR", "OFFROAD"
  ]
};

// Returns a random sample of words of direct count from a custom or embedded theme list
export function getSampleWords(themeName: string, count: number): string[] {
  const normTheme = themeName.toUpperCase().trim();
  const wordPool = embeddedThemes[normTheme] || embeddedThemes["ANIMAIS"];
  
  // Clean, shuffle, and sample
  const cleaned = wordPool
    .map(w => cleanWord(w))
    .filter(w => w.length >= 4 && w.length <= 15);
    
  const shuffled = [...cleaned].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

// Function to clean words as requested: removes accent, non-letters, spaces, duplicates
export function cleanWord(word: string): string {
  return word
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // remove accent marks
    .replace(/Ç/g, "C")
    .replace(/[^A-Z]/g, "") // remove special chars, hifens, spaces
    .trim();
}

// Helper to fuzzy match an entered theme to one of our 10 embedded high quality themes
export function matchOfflineTheme(themeName: string): string | null {
  const normalized = themeName
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^A-Z]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  const keywords: Record<string, string[]> = {
    ANIMAIS: ["ANIMAL", "CAO", "GATO", "BALEIA", "LEAO", "BICHO", "ANIMALS", "PET", "ZOOLOGICO", "FAUNA", "SELVA", "SAURO", "CACHORRO", "PASSARO", "INSETO", "PEIXE"],
    FRUTAS: ["FRUTA", "MACA", "LARANJA", "BANANA", "UVA", "SALADA DE FRUTA", "FRUIT", "SOBREMESA", "ALIMENTO", "MORANGO", "ABACAXI", "DOCE", "MELANCIA"],
    PAISES: ["PAIS", "ESTADO", "BRASIL", "ALEMANHA", "EUA", "EUROPA", "AMERICA", "NACAO", "NACION", "MONDO", "MAPA", "GEOGRAFIA", "PORTUGAL", "FRANCA", "JAPAO"],
    PROFISSOES: ["PROFISSAO", "TRABALHO", "EMPREGO", "MEDICO", "ADVOGADO", "ENGINEER", "CARREIRA", "VAGA", "OFICIO"],
    TECNOLOGIA: ["TECNOLOGIA", "COMPUTADOR", "SOFTWARE", "NET", "WEB", "CELULAR", "AI", "IA", "TECH", "DIGITAL", "DADOS", "ALGORITMO", "SISTEMA", "ROBO", "VIDEO"],
    ESPORTES: ["ESPORTE", "FUTEBOL", "JOGO", "BASQUETE", "TENIS", "CORRIDA", "SPORTS", "RECREACAO", "ATLETA", "NATACAO", "GINASTICA", "CORRE"],
    MÚSICA: ["MUSICA", "CANTOR", "MELODIA", "BANDA", "SONG", "MUSIC", "INSTRUMENTO", "ROCK", "POP", "CANCAO", "SOM", "AUDIO", "SHOW"],
    FILMES: ["FILME", "CINEMA", "DIRETOR", "OSCAR", "MOVIE", "HOLLYWOOD", "SERIE", "ATORES", "ROTEIRO", "PRODUTORA", "PIPOCA", "CLAQUETE"],
    CIENCIAS: ["CIENCIA", "ATOMO", "BIOLOGIA", "FISICA", "QUIMICA", "SCIENCE", "PLANETA", "ESPACO", "UNIVERSO", "LABORATORIO", "PESQUISA", "ESTUDO", "VACINA"],
    VEICULOS: ["VEICULO", "CARRO", "AVIAO", "MOTO", "ONIBUS", "TRANSPORTE", "VAGAO", "ESTRADA", "VIAGEM", "FREIO", "BARCO", "MOTOR"]
  };

  for (const [theme, list] of Object.entries(keywords)) {
    if (normalized.includes(theme) || theme.includes(normalized)) {
      return theme;
    }
    for (const kw of list) {
      if (normalized.includes(kw) || kw.includes(normalized)) {
        return theme;
      }
    }
  }
  return null;
}
